### ISSUE TITLE
Rebooting a crashed Pod

### ISSUE THREAD

**Issue by AntoineOrsoni** [CiscoDevNet/devnet-express-dna-issues#113]
Could I have access to dCloud admin platform, so I can reboot an unreachable pod instead of replacing it?

**Comment by klevenstein** [comment]
Hi @AntoineOrsoni - please contact dCloud support at dcloud-support@cisco.com. Thanks!

**Comment by RuthCattell** [comment]
@klevenstein  - Antoine's question is more about 'is it possible to reboot an unreachable pod instead of replacing it?'  There's a way of doing this without having access to dCloud DevNet account I think.  I'll reach out to you separately about this so and then - if there is - we can provide instructions to trainers moving forward.    Thanks.
