### ISSUE TITLE
Store lab environment information in the environment

### ISSUE THREAD

**Issue by cmlccie** [CiscoDevNet/devnet-express-dna-issues#24]
We repeatedly do some of the same information retrieval exercises over and over:

- Copy and paste your Spark Access Token into your script (bad practice - storing credentials in code)
- Get the Room ID of the Spark Room to which you want your script to post
- Get the IP address / hostname of XYZ host...
- Get the Username and Password for XYZ host...

All of this information could be collected and stored once in the participant's development environment, which would reduce duplicate work for the participants and streamline some of the scripts (which could for example simply access the participant's `SPARK_ACCESS_TOKEN` environment variable for example).

We could provide a sample `environment_variables.sh` and `environment_variables.bat` pre-populated with the dCloud environment information (hostnames, credentials and etc.) and placeholders for the participant's unique information (Spark Access Token, Room ID, etc.).  These files could then be easily sourced / executed to setup their environment in preparation for them running their code.

**Comment by brtiller1** [comment]
Since several scripts I’ve written ask users to post their token into the code, I’ll respond by saying that we clearly know this is a bad practice and we tell users that from the beginning with the slide that says this is just sample code and real code should be written differently and with much more error checking, but for learning purposes we are keeping everything simple and clear.

That said,  I like the environment variables idea as long as it is well tested first for all OS’s before being rolled out.  We’ll need to modify some of scripts to account for this change which should be done all at once like the repeal/replace idea. ☺

Brett
[http://www.cisco.com/web/europe/images/email/signature/logo05.jpg]

Brett Tiller
ENGINEER.CUSTOM APPLICATION
brtiller@cisco.com
Phone: +1 919 392 3307
DevNet
http://developer.cisco.com

Cisco Systems Limited
7025-6 Kit Creek Road PO Box 14987
RESEARCH TRIANGLE PARK
NORTH CAROLINA
27709-4987
US

**Comment by dstaudt** [comment]
DNE/CC has only had the one live event, but it was definitely harder for 
folks to grasp the environment variable script concept, and users ran 
into problems, especially cross-platform.  We actually decided to switch 
to the in-script method for simplicity's sake.

Not particularly saying this is how we should proceed globally, just an 
observation.  There are all kinds of other best-practices we are 
probably breaking/avoiding (bidirectional certificate checking, proper 
error-handling, request throttling) as well...

I am loath to show people the 'wrong way' though, so if you guys are 
successful in going the env-var route, we'll probably take the cue.

Regards,
- David Staudt

**Comment by klevenstein** [comment]
Labs and the code for them have evolved significantly in the last three (!) years since this was touched last; closing.
