### ISSUE TITLE
devnet-express-code-samples - Consistency and Code Quality

### ISSUE THREAD

**Issue by cmlccie** [CiscoDevNet/devnet-express-dna-issues#25]
As we are teaching / helping participants get started with coding, we should strive to set the example for code quality and readability in our provided sample code that participants are reading and working with.  Doing so:

+ Helps gets participants off to a good start with good coding habits
+ Demonstrates our knowledge and expertise, and establishes Cisco as a capable thought-leader in the area of infrastructure programmability
+ Following established conventions helps improve the readability and updatability of our code

Python has established coding conventions [PEP 8 -- Style Guide for Python Code](https://www.python.org/dev/peps/pep-0008/), documentation conventions [PEP 257 -- Docstring Conventions](https://www.python.org/dev/peps/pep-0257/), and guiding principles [PEP 20 -- The Zen of Python](https://www.python.org/dev/peps/pep-0020/). 

Tremendous global thought has gone into these conventions and principles, and these recommendations net-out in an improved coding experience when coding with Python.

Some of the issues that participants have faced when working with our sample scripts:

- Indentation errors
- Not understanding what the intent of a provided function is
- Not understanding what type of data is being passed into or returned by a function
- Not understanding the flow / execution of one script as compared to previous one
- Not checking for returned API errors, and raising appropriate exceptions
- Silencing errors

Would be greatly mitigated by our adherence these established conventions and principles.

Adherence to PEP8 conventions can be check programmatically / automatically by using a good code linter (like [pep8](https://pypi.python.org/pypi/pep8) or [flake8](https://pypi.python.org/pypi/flake8)).

## PEP8 report for devnet-express-code-samples
``` bash
(dne4dna) dne4dna $ pep8 --statistics -qq ./devnet-express-code-samples/
56      E101 indentation contains mixed spaces and tabs
43      E111 indentation is not a multiple of four
5       E116 unexpected indentation (comment)
9       E122 continuation line missing indentation or outdented
4       E127 continuation line over-indented for visual indent
4       E128 continuation line under-indented for visual indent
2       E201 whitespace after '('
3       E202 whitespace before ')'
1       E203 whitespace before ':'
53      E211 whitespace before '('
9       E221 multiple spaces before operator
7       E223 tab before operator
171     E225 missing whitespace around operator
721     E231 missing whitespace after ','
16      E251 unexpected spaces around keyword / parameter equals
16      E261 at least two spaces before inline comment
15      E262 inline comment should start with '# '
46      E265 block comment should start with '# '
8       E266 too many leading '#' for block comment
34      E302 expected 2 blank lines, found 1
22      E303 too many blank lines (3)
10      E402 module level import not at top of file
204     E501 line too long (93 > 79 characters)
14      E703 statement ends with a semicolon
16      E711 comparison to None should be 'if cond is None:'
330     W191 indentation contains tabs
106     W291 trailing whitespace
17      W292 no newline at end of file
56      W293 blank line contains whitespace
8       W391 blank line at end of file
```

**The indentation issues are of practical concern for DNE participants** as indentation is syntactically significant in Python, and when combined with the default editor preferences in the text editors that many participants use (including our dCloud environment), participants receive needless indentation errors when updating and working with our sample code files.

**Most of the rest of these reported 'issues'** are simply 'Python coding style' errors that if corrected would improve the image of Cisco and DevNet and teach participants good habits, but otherwise are not functional issues.

**Asks / Recommendations:**

1. Correct the inconsistent indentation in our sample code
2. Provide good minimally necessary error checking
3. As we have energy or interest to do, and especially when creating new / additional sample code, work to adhere to established industry coding practices and style.

**Comment by brtiller1** [comment]
Chris I like your motivated spirit.  I agree on the part of indentation consistency (tabs versus spaces) which can be easily improved in our scripts, and we can be more consistent with spacing and such.  That said, we are not teaching a college level semester long course.  Our goal during a one day training event, 60-90 minutes per session, is to expose attendees to programming concepts to get them started which means that we should keep things as simple as reasonably possible and not get lost in the details of coding standards for newbies or near newbies.  Adding error checking is going to only make the code harder to comprehend for newbies.


  *   Indentation errors
     *   [Brett] Agreed this should be addressed.
  *   Not understanding what the intent of a provided function is
     *   [Brett] Instructor and lab content should provide this explanation.
  *   Not understanding what type of data is being passed into or returned by a function
     *   [Brett] Users will understand this detail better after learning the Python fundamentals covered in our Python module.  This module can easily be expanded to include more details with new labs.
  *   Not understanding the flow / execution of one script as compared to previous one
     *   [Brett]  Please provide more details/examples.
  *   Not checking for returned API errors, and raising appropriate exceptions
     *   [Brett]  Suggest we don’t add error checking as will confuse newbies.  In advanced labs this error checking can be added.
  *   Silencing errors
     *   [Brett]  Please show where errors are being silenced.

Brett
[http://www.cisco.com/web/europe/images/email/signature/logo05.jpg]

Brett Tiller
ENGINEER.CUSTOM APPLICATION
brtiller@cisco.com
Phone: +1 919 392 3307
DevNet
http://developer.cisco.com

Cisco Systems Limited
7025-6 Kit Creek Road PO Box 14987
RESEARCH TRIANGLE PARK
NORTH CAROLINA
27709-4987
US

**Comment by cmlccie** [comment]
I'm not suggesting that we add in teaching these conventions, but rather that our code should teach by example.

Regarding error checking...  Which would you find easier to debug:
_<run this and check out the difference; commenting out the first json_dict line>_

``` python
import requests

response = requests.get('https://api.ciscospark.com/v1/people')

# Which is a more useful exception for a participant to debug?

# Current non-checking method:
json_dict = response.json()


# Minimal error-state checking:
if response.status_code == 200:
	json_dict = response.json()
else:
	response.raise_for_status()
```

**Comment by dstaudt** [comment]
+1 on style/consistency in a 'by example' way

+1 for minimal (though perhaps not always optimal) error checking to 
catch basic/common issues

Regards,
- David Staudt

**Comment by brtiller1** [comment]
Chris, your ideas are on point, but too advanced for newbies/near newbie developers, and I think would lead to confusion.  For example, the code response.raise_for_status() throws an exception which means that we would need to teach exception handling, try/catch/finally blocks and so forth to adequately cover that concept.  I don’t support teaching that to newbies/near newbies because for every two that get it, another ten will be left confused and/or overwhelmed with too much data to absorb.

We already get some complaints that we’re pushing too much knowledge.  For experienced developers I support several of your ideas, and think they would be best applied to our upcoming advanced labs.  For our beginner level labs we should keep them as simple as possible with no added error checking wherever possible.

Brett
[http://www.cisco.com/web/europe/images/email/signature/logo05.jpg]

Brett Tiller
ENGINEER.CUSTOM APPLICATION
brtiller@cisco.com
Phone: +1 919 392 3307
DevNet
http://developer.cisco.com

Cisco Systems Limited
7025-6 Kit Creek Road PO Box 14987
RESEARCH TRIANGLE PARK
NORTH CAROLINA
27709-4987
US

**Comment by brtiller1** [comment]
Err…I meant try/except/finally blocks – reliving my old java programming days. ☺

[http://www.cisco.com/web/europe/images/email/signature/logo05.jpg]

Brett Tiller
ENGINEER.CUSTOM APPLICATION
brtiller@cisco.com
Phone: +1 919 392 3307
DevNet
http://developer.cisco.com

Cisco Systems Limited
7025-6 Kit Creek Road PO Box 14987
RESEARCH TRIANGLE PARK
NORTH CAROLINA
27709-4987
US




From: Brett Tiller (brtiller)
Sent: Tuesday, April 18, 2017 5:11 PM
To: 'CiscoDevNet/devnet-express-dna-issues'; CiscoDevNet/devnet-express-dna-issues
Cc: Comment
Subject: RE: [CiscoDevNet/devnet-express-dna-issues] devnet-express-code-samples - Consistency and Code Quality (#25)

Chris, your ideas are on point, but too advanced for newbies/near newbie developers, and I think would lead to confusion.  For example, the code response.raise_for_status() throws an exception which means that we would need to teach exception handling, try/catch/finally blocks and so forth to adequately cover that concept.  I don’t support teaching that to newbies/near newbies because for every two that get it, another ten will be left confused and/or overwhelmed with too much data to absorb.

We already get some complaints that we’re pushing too much knowledge.  For experienced developers I support several of your ideas, and think they would be best applied to our upcoming advanced labs.  For our beginner level labs we should keep them as simple as possible with no added error checking wherever possible.

Brett
[http://www.cisco.com/web/europe/images/email/signature/logo05.jpg]

Brett Tiller
ENGINEER.CUSTOM APPLICATION
brtiller@cisco.com<mailto:brtiller@cisco.com>
Phone: +1 919 392 3307
DevNet
http://developer.cisco.com

Cisco Systems Limited
7025-6 Kit Creek Road PO Box 14987
RESEARCH TRIANGLE PARK
NORTH CAROLINA
27709-4987
US

**Comment by aradford123** [comment]
I agree with Brett.

The basic labs are so simple that they should just work.

I think part of the learning/skill development process is to appreciate error checking as well.

KISS

**Comment by cmlccie** [comment]
I don't think you guys get it...

They are running into errors today.  Less descriptive and less useful errors.  I'm not saying to catch them or teach them how to catch them.  I was asking that we provide minimal response code checking so that, when something is wrong - yes an error is raised, but it is a more descriptive and easier to troubleshoot error than what they are getting today.

It takes elegant sophistication to provide a clean and intuitive UX.  I'm not talking about teaching them more that what we are doing today, though in my Python Primer sessions I did teach some very basic troubleshooting to help them understand what is going on when they run into errors, I'm thinking interns of:

Here is their learning UX today...
What challenges do they run into?
Are they adequately prepared with how to approach or troubleshoot that challenge?
What can be done to improve their learning UX and increase their confidence.

Perhaps it is just a matter of understanding how to communicate complex topics in simple terms that begin people down the road of understanding without telling them the whole journey.

Chris Lunsford
WWSE Programmability Lead @ Cisco
@cmlccie | +1 (865) 671-5605

Sent from my iPhone.  Please excuse typos.

**Comment by brtiller1** [comment]
Chris,

When I taught the Python/APIC-EM DNE sessions the only issues I’ve seen were the occasional spaces versus tabs issue, and a pod might be unresponsive in which case we issued the user a new one.  If you’re seeing new common issues we should determine why they are occurring first.

Second, understand that most people are not as sharp as you are and don’t pick up things as quickly.  Providing code that they don’t understand and telling them about troubleshooting/exception handling for instance is going to go over most people’s heads.  People learn by hearing/seeing and doing which is the reason for not just telling them, but showing them how to do things and then having them do it through the hands-on labs.

As I’ve already stated, we already get some complaints that we are pushing too much knowledge, so I still vote to keep things as simple as possible – KISS , and reserve the more complex things for the more advanced training planned for the future.

Brett

[http://www.cisco.com/web/europe/images/email/signature/logo05.jpg]

Brett Tiller
ENGINEER.CUSTOM APPLICATION
brtiller@cisco.com
Phone: +1 919 392 3307
DevNet
http://developer.cisco.com

Cisco Systems Limited
7025-6 Kit Creek Road PO Box 14987
RESEARCH TRIANGLE PARK
NORTH CAROLINA
27709-4987
US

**Comment by aradford123** [comment]
Agree.

For slow learners like me, the best way to learn is through my mistakes in a simple environment.

I actually don't learn much from being spoon fed.

**Comment by cmlccie** [comment]
Thanks guys.  I appreciate your perspective.  I'm really not talking about spoon feeding anyone; I too learn more when things break than when everything goes to plan.  However, if I'm going to intentionally put 'learning moments' in my learning material, I want it to be intentional and not accidental because I could have coded it better.  My request for minimal error checking was an attempt to give the participants descriptive errors that point them in the right direction vs. an error that confuses and could send them on a wild goose chase (a 404 error is more accurate than a JSON error that was caused by the script receiving a 404 returned status code).

I'm guessing that neither of you ran my code sample.

In any case this issue is about us writing as clean, simple and well formatted code as possible.  I have yet to hear a defense saying why we should ignore industry style and coding practices.

**Comment by austinMarcos** [comment]
The solution to improving the code quality is being addressed by an initiative led by Chris L and Marcos. See the repo:
> https://github.com/CiscoDevNet/content-process-and-standards
