### ISSUE TITLE
LM-4402: REST APIs - Authentication in new Postman GUI

### ISSUE THREAD

**Issue by pmorvay** [CiscoDevNet/devnet-express-dna-issues#33]
Hello, I have recently installed Postman and the GUI seems different, I can not see, how to paste/import the token and maybe, because of this I can not set content type

Could you please update part:
LM-4402: REST APIs
  - Overview of REST APIs In Progress
    - Step 4. Use Postman to Call the Spark API

Thanks

**Comment by brtiller1** [comment]
Hi Peter,

There should be a scroll bar on the right side of the screen so that you can view and set the headers.  If not, please send a screenshot.

Brett

[http://www.cisco.com/web/europe/images/email/signature/logo05.jpg]

Brett Tiller
ENGINEER.CUSTOM APPLICATION
brtiller@cisco.com
Phone: +1 919 392 3307
DevNet
http://developer.cisco.com

Cisco Systems Limited
7025-6 Kit Creek Road PO Box 14987
RESEARCH TRIANGLE PARK
NORTH CAROLINA
27709-4987
US

**Comment by pmorvay** [comment]
Sorry, it was my mistake, I saw authorization button, but Actually needed to set authorization as a value in the header
